### ISSUE TITLE
Hunspell Dictionary

### ISSUE THREAD

**Issue by MayuraVerma** [sanskrit-coders/stardict-kannada#2]
Hello,

I have a decent set of Kannada dictionary in hunspell format. How do I contribute?

Is stardict format the best or fast format cross all platform?

If we want to further enhance the dictionary with more attributes, is this a better format. 

Mac and Windows has their own native API to build custom dictionary. Building stardict will it make difficult to eventually translate to the native format of these OS's?

Thanks for the good work.

Looking forward to contribute to this project.

**Comment by vvasuki** [comment]
namaste @MayuraVerma . ನಿಮಗಿಲ್ಲ್ಲಿ ಸ್ವಾಗತ. 

First, you should understand the difference between a
* "dictionary used to look up things" (stardict, babylon, etc..) and 
* "a so called dictionary, which is basically a word list used for spelling correction" (hunspell etc..).

This project is about the former, but what you have seems to be the latter. hunspell dictionaries are separately useful, I encourage you to create a repository such as https://github.com/Shreeshrii/hindi-hunspell and publish it. If you get a dictionary of the former type, please let us know by opening an issue.

If this answer is satisfactory, please close the thread too.

**Comment by MayuraVerma** [comment]
OK. does this stardict can it be used for spell check, suggestions and auto-correction features in the OS, Windows and Mac?

Or can it be used only for standalone dictionary application?

I will contribute to the other project.

Please let me know how I can contribute here. Do you intend to open this dictionary for community editing and reviewing.

**Comment by vvasuki** [comment]
@MayuraVerma  - the stardict dictionary by itself is incompatible with spell-check/ suggestion/ correction software. But, data from the dictionary can be exported to improve files in hunspell format.

> Please let me know how I can contribute here.

Depends on what your skills and interests are..

> Do you intend to open this dictionary for community editing and reviewing.

For that we already have wiktionary. One only needs to periodically construct a stardict dictionary from wiktionary dumps.
